"""PDF report generator for AI Act supporting documentation."""

from datetime import datetime
from pathlib import Path
from typing import Optional, Union

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from uncertainty_module.core.engine import OversightResult, RiskLevel


class SupportingDocumentation:
    """Generator for AI Act supporting documentation PDFs."""
    
    def __init__(self, company_name: str = "Medical AI Systems Inc."):
        self.company_name = company_name
        self.styles = getSampleStyleSheet()
        self._setup_styles()
        
    def _setup_styles(self) -> None:
        """Setup custom paragraph styles."""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=18,
            spaceAfter=20,
            textColor=colors.HexColor('#1a365d'),
        ))
        
    def generate(
        self,
        result: OversightResult,
        output_path: Union[str, Path],
    ) -> str:
        """Generate a PDF supporting documentation."""
        output_path = Path(output_path)
        
        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=A4,
            rightMargin=2*cm,
            leftMargin=2*cm,
            topMargin=2*cm,
            bottomMargin=2*cm,
        )
        
        story = []
        self._add_header(story)
        self._add_summary(story, result)
        self._add_uncertainty_table(story, result)
        self._add_risk_assessment(story, result)
        self._add_footer(story)
        
        doc.build(story)
        return str(output_path)
        
    def _add_header(self, story: list) -> None:
        """Add document header."""
        story.append(Paragraph(
            "AI Act Supporting Documentation",
            self.styles['CustomTitle']
        ))
        story.append(Paragraph(
            f"Generated by: {self.company_name}",
            self.styles['Normal']
        ))
        story.append(Paragraph(
            f"Date: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}",
            self.styles['Normal']
        ))
        story.append(Spacer(1, 0.5*cm))
        
    def _add_summary(self, story: list, result: OversightResult) -> None:
        """Add executive summary."""
        story.append(Paragraph("Executive Summary", self.styles['Heading2']))
        
        risk_colors = {
            RiskLevel.LOW: 'green',
            RiskLevel.MEDIUM: '#d69e2e',
            RiskLevel.HIGH: 'orange',
            RiskLevel.CRITICAL: 'red',
        }
        risk_color = risk_colors.get(result.uncertainty.risk_level, 'black')
        
        summary = f"""
        <b>Image ID:</b> {result.image_id}<br/>
        <b>Prediction:</b> {result.prediction}<br/>
        <b>Confidence:</b> {result.prediction_probability:.1%}<br/>
        <b>Risk Level:</b> <font color="{risk_color}">{result.uncertainty.risk_level.value.upper()}</font><br/>
        <b>Human Review Required:</b> {'Yes' if result.requires_human_review else 'No'}<br/>
        """
        story.append(Paragraph(summary, self.styles['Normal']))
        story.append(Spacer(1, 0.3*cm))
        
    def _add_uncertainty_table(self, story: list, result: OversightResult) -> None:
        """Add uncertainty metrics table."""
        story.append(Paragraph("Uncertainty Metrics", self.styles['Heading2']))
        
        unc = result.uncertainty
        data = [
            ['Metric', 'Value'],
            ['Total Uncertainty', f'{unc.total_uncertainty:.4f}'],
            ['Aleatoric Uncertainty', f'{unc.aleatoric_uncertainty:.4f}'],
            ['Epistemic Uncertainty', f'{unc.epistemic_uncertainty:.4f}'],
            ['Confidence Score', f'{unc.confidence_score:.4f}'],
        ]
        
        table = Table(data, colWidths=[6*cm, 4*cm])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2c5282')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ]))
        
        story.append(table)
        story.append(Spacer(1, 0.3*cm))
        
    def _add_risk_assessment(self, story: list, result: OversightResult) -> None:
        """Add risk assessment section."""
        story.append(Paragraph("Risk Assessment", self.styles['Heading2']))
        
        if result.requires_human_review:
            story.append(Paragraph(
                f"<b>Decision:</b> <font color='orange'>REQUIRES HUMAN REVIEW</font>",
                self.styles['Normal']
            ))
            story.append(Paragraph("<b>Reasons:</b>", self.styles['Normal']))
            for reason in result.override_reasons:
                story.append(Paragraph(f"• {reason}", self.styles['Normal']))
        else:
            story.append(Paragraph(
                "<b>Decision:</b> <font color='green'>APPROVED FOR AUTONOMOUS OPERATION</font>",
                self.styles['Normal']
            ))
            
        story.append(Spacer(1, 0.2*cm))
        story.append(Paragraph(
            f"<b>95% Confidence Interval:</b> [{result.confidence_interval[0]:.4f}, {result.confidence_interval[1]:.4f}]",
            self.styles['Normal']
        ))
        
    def _add_footer(self, story: list) -> None:
        """Add footer with compliance info."""
        story.append(Spacer(1, 1*cm))
        story.append(Paragraph(
            "<i>This document supports EU AI Act Articles 14 & 15 compliance.</i>",
            self.styles['Normal']
        ))
